# **4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

In [2]:
import numpy as np

In [3]:


arr = np.empty((3, 3))
print(arr)


[[4.77183458e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [4]:
array = np.ones((4,2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
a = np.full([2, 2], 67, dtype = int) #shape, fill value, type
print("\nMatrix a : \n", a)


Matrix a : 
 [[67 67]
 [67 67]]


In [6]:
my_array = np.array([[1,2,3],[4,5,6]])
zeros_array = np.zeros_like(my_array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [7]:
my_array = np.array([[1,2,3],[4,5,6]])
ones_array = np.ones_like(my_array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [8]:
my_list = [1,2,3,4]
my_arr = np.array(my_list)
print(my_arr)

[1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing**

In [9]:
arr = np.arange(11,50)
print(arr)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
iden = np.eye(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
rand_array = np.random.random(size=30)
print(rand_array)
print("The mean of the above array is: ",rand_array.mean())

[0.61133331 0.71341691 0.82945028 0.42656364 0.75612803 0.10802443
 0.87052061 0.37348557 0.18978426 0.23417048 0.14412306 0.65566142
 0.69824507 0.58056317 0.65073094 0.62508417 0.36130703 0.69811132
 0.78508141 0.89416851 0.28128664 0.92914252 0.71179291 0.14363946
 0.76132728 0.42250149 0.15234469 0.93433152 0.91762379 0.80029189]
The mean of the above array is:  0.5753411934265997


In [13]:
rand_array = np.random.random((10,10))
print(rand_array)
print("Minimum Value is ",rand_array.min())
print("Maximum Value is ",rand_array.max())

[[0.90111959 0.71753543 0.47014725 0.70464948 0.99760271 0.1405548
  0.15361874 0.57081148 0.52831521 0.26224753]
 [0.98181607 0.7384377  0.76364254 0.42678303 0.35476801 0.6818434
  0.89095232 0.4297856  0.55794907 0.53700451]
 [0.62793262 0.98164878 0.01911879 0.78494143 0.11205523 0.11794217
  0.12231136 0.27446139 0.10488065 0.81851456]
 [0.52978381 0.77659358 0.58316724 0.06248098 0.3548338  0.30804282
  0.86652642 0.62879484 0.33458932 0.0890782 ]
 [0.60774587 0.02613144 0.60747107 0.70533178 0.0583098  0.24350509
  0.29964501 0.19718858 0.31798767 0.8022981 ]
 [0.90763819 0.24216235 0.82489586 0.03282644 0.42902655 0.17942427
  0.95540771 0.10398591 0.34371511 0.97997532]
 [0.12533116 0.80108851 0.38408085 0.14916013 0.03961158 0.35393546
  0.9542917  0.78149703 0.64266954 0.31392039]
 [0.98240961 0.73253733 0.93313123 0.82913362 0.57151447 0.29866784
  0.95986835 0.00231384 0.16413132 0.47018701]
 [0.59845308 0.90146979 0.96286774 0.89829838 0.85794769 0.19864489
  0.36829044 0

In [14]:
zero_arr = np.zeros(10)
print(zero_arr)
zero_arr[5]=1
print(zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [15]:
arr = [1,2,0,0,4,0]
rev = np.flip(arr)
print(rev)

[0 4 0 0 2 1]


In [16]:
array = np.zeros((5, 5), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Top border
array[-1, :] = 1  # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1  # Right border

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [17]:
import numpy as np

# Create an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
checkerboard[::2, ::2] = 1  # Fill 1 at even rows and even columns
checkerboard[1::2, 1::2] = 1  # Fill 1 at odd rows and odd columns

print(checkerboard)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


**Problem - 3: Array Operations:**

In [18]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Arrays:")
print("x =", x)
print("y =", y)
print("v =", v)
print("w =", w)
print()


Arrays:
x = [[1 2]
 [3 5]]
y = [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]



In [19]:
print("1. Addition of x and y:")
print(x + y)

print("2. Subtraction of y from x:")
print(x - y)

print("3. Multiply x by 2:")
print(x * 2)

print("4. Square of each element in x:")
print(np.square(x))


1. Addition of x and y:
[[ 6  8]
 [10 13]]
2. Subtraction of y from x:
[[-4 -4]
 [-4 -3]]
3. Multiply x by 2:
[[ 2  4]
 [ 6 10]]
4. Square of each element in x:
[[ 1  4]
 [ 9 25]]


In [20]:
print("5. Dot products:")
print("v . w =", np.dot(v, w))
print("x . v =")
print(np.dot(x, v))
print("x . y =")
print(np.dot(x, y))


5. Dot products:
v . w = 219
x . v =
[29 77]
x . y =
[[19 22]
 [50 58]]


In [21]:
concat_xy = np.concatenate((x, y), axis=0)  # Along rows
concat_vw = np.vstack((v, w))  # Along columns
print("Concatenation of x and y: ",concat_xy)
print("Concatenation of v and w: ",concat_vw)



Concatenation of x and y:  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w:  [[ 9 10]
 [11 12]]


In [22]:
try:
    result = np.concatenate((x, v), axis=0)
    print(result)
except ValueError as e:
    print(f"Error occurred: {e}")

Error occurred: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


The error occured because x and v have different dimensions i.e. x has 2 row and v doesnt have same row. Thererfore, the number of rows and columns must be same in order to concatinate two arrays.

**Problem - 4: Matrix Operations:**

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
B_T_A_T = np.dot(B_T, A_T)

are_equal = np.array_equal(AB_T, B_T_A_T)

print("(AB)^T:", AB_T)
print("B^T A^T:", B_T_A_T)
print("Is (AB)^T equal to B^T A^T? ", are_equal)

(AB)^T: [[19 43]
 [22 50]]
B^T A^T: [[19 43]
 [22 50]]
Is (AB)^T equal to B^T A^T?  True


In [24]:
import time

list1, list2 = range(1_000_000), range(1_000_000)
start = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
time_list = time.time() - start

array1, array2 = np.arange(1_000_000), np.arange(1_000_000)
start = time.time()
array_sum = array1 + array2
time_numpy = time.time() - start

print(f"Python lists: {time_list:.3f}s, NumPy arrays: {time_numpy:.3f}s")

Python lists: 0.147s, NumPy arrays: 0.005s


In [25]:
list1, list2 = range(1_000_000), range(1_000_000)

start = time.time()
list_product = [x * y for x, y in zip(list1, list2)]
time_list = time.time() - start

array1, array2 = np.arange(1_000_000), np.arange(1_000_000)

start = time.time()
array_product = array1 * array2
time_numpy = time.time() - start

print(f"Python lists: {time_list:.3f}s, NumPy arrays: {time_numpy:.3f}s")

Python lists: 0.174s, NumPy arrays: 0.006s


**EXPERIMENT**

In [30]:
import time

# Function to measure time taken for an operation
def measure_time(func):
    start_time = time.time()
    func()
    end_time = time.time()
    return end_time - start_time

1. Element-wise Addition

In [33]:
def addition_python():
    list1 = [i for i in range(1_000_000)]
    list2 = [i for i in range(1_000_000)]
    result = [list1[i] + list2[i] for i in range(len(list1))]
def addition_numpy():
    arr1 = np.arange(1_000_000)
    arr2 = np.arange(1_000_000)
    result = arr1 + arr2

print("Element-wise Addition: ")
print(f"Python lists took {measure_time(addition_python):.6f} seconds")
print(f"Numpy array took {measure_time(addition_numpy):.6f} seconds")

Element-wise Addition: 
Python lists took 0.278781 seconds
Numpy array took 0.009767 seconds


2. Element-wise Multiplication

In [32]:
def multiplication_python():
    list1 = [i for i in range(1_000_000)]
    list2 = [i for i in range(1_000_000)]
    result = [list1[i] * list2[i] for i in range(len(list1))]

def multiplication_numpy():
    arr1 = np.arange(1_000_000)
    arr2 = np.arange(1_000_000)
    result = arr1 * arr2

print("Element-wise Multiplication:")
print(f"Python lists took {measure_time(multiplication_python):.6f} seconds")
print(f"Numpy array took {measure_time(multiplication_numpy):.6f} seconds")

Element-wise Multiplication:
Python lists took 0.356494 seconds
Numpy array took 0.010231 seconds


3. Dot Product

In [34]:
def dot_product_python():
    list1 = [i for i in range(1_000_000)]
    list2 = [i for i in range(1_000_000)]
    result = sum(list1[i] * list2[i] for i in range(len(list1)))

def dot_product_numpy():
    arr1 = np.arange(1_000_000)
    arr2 = np.arange(1_000_000)
    result = np.dot(arr1, arr2)

print("Dot Product:")
print(f"Python lists took {measure_time(dot_product_python):.6f} seconds")
print(f"Numpy array took {measure_time(dot_product_numpy):.6f} seconds")

Dot Product:
Python lists took 0.253449 seconds
Numpy array took 0.030346 seconds


4. Matrix Multiplication

In [35]:
def matrix_multiplication_python():
    mat1 = [[j for j in range(1000)] for i in range(1000)]
    mat2 = [[j for j in range(1000)] for i in range(1000)]
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*mat2)] for row in mat1]

def matrix_multiplication_numpy():
    mat1 = np.arange(1000*1000).reshape(1000, 1000)
    mat2 = np.arange(1000*1000).reshape(1000, 1000)
    result = np.dot(mat1, mat2)

print("Matrix Multiplication:")
print(f"Python lists took {measure_time(matrix_multiplication_python):.6f} seconds")
print(f"Numpy array took{measure_time(matrix_multiplication_numpy):.6f} seconds")

Matrix Multiplication:
Python lists took 210.012163 seconds
Numpy array took2.127786 seconds


Hence, in every experiment numpy proves to be a lot faster specially while permforming matrix multiplication.