# **4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

In [2]:
import numpy as np

In [ ]:


arr = np.empty((3, 3))
print(arr)


[[5.01406124e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
array = np.ones((4,2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a = np.full([2, 2], 67, dtype = int) #shape, fill value, type
print("\nMatrix a : \n", a)


Matrix a : 
 [[67 67]
 [67 67]]


In [ ]:
my_array = np.array([[1,2,3],[4,5,6]])
zeros_array = np.zeros_like(my_array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [ ]:
my_array = np.array([[1,2,3],[4,5,6]])
ones_array = np.ones_like(my_array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [ ]:
my_list = [1,2,3,4]
my_arr = np.array(my_list)
print(my_arr)

[1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing**

In [ ]:
arr = np.arange(11,50)
print(arr)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
iden = np.eye(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
rand_array = np.random.random(size=30)
print(rand_array)
print("The mean of the above array is: ",rand_array.mean())

[0.01783479 0.21447172 0.13399751 0.17396424 0.31309838 0.5061609
 0.65401059 0.86420719 0.0922379  0.58794806 0.87934306 0.27280655
 0.17216388 0.04291684 0.03886279 0.70968545 0.98634003 0.03622323
 0.25038918 0.07157621 0.10382111 0.65593762 0.10947488 0.03958638
 0.73678358 0.61049856 0.78994746 0.7780533  0.03048165 0.07234617]
The mean of the above array is:  0.3648389736865406


In [ ]:
rand_array = np.random.random((10,10))
print(rand_array)
print("Minimum Value is ",rand_array.min())
print("Maximum Value is ",rand_array.max())

[[0.30283869 0.41378979 0.36213135 0.06475578 0.18481021 0.93877517
  0.75938268 0.75062714 0.06541184 0.95564402]
 [0.442098   0.30769317 0.99087238 0.78282625 0.468726   0.98185464
  0.0735597  0.69387752 0.26978578 0.58254829]
 [0.94485925 0.28433715 0.38723712 0.44092156 0.38393789 0.22826381
  0.80246766 0.41052581 0.78960359 0.75824741]
 [0.35536978 0.9249491  0.58965066 0.49658367 0.41098797 0.16020776
  0.91453614 0.88234478 0.06125539 0.56586631]
 [0.35651571 0.82986817 0.4035552  0.13654778 0.33017981 0.13049018
  0.29951345 0.78752589 0.76302545 0.82742032]
 [0.89850438 0.12912812 0.14399291 0.73930388 0.64191016 0.5325107
  0.46485208 0.50500551 0.70699425 0.84672791]
 [0.06367327 0.2691381  0.93420401 0.22880816 0.01818373 0.59041877
  0.56029178 0.66141093 0.18297359 0.73767598]
 [0.62168451 0.13461374 0.231539   0.8749315  0.66676603 0.5063979
  0.68555623 0.83648106 0.07506537 0.95765909]
 [0.53475037 0.99772469 0.78150871 0.4433121  0.5039912  0.45224952
  0.80714195 0

In [ ]:
zero_arr = np.zeros(10)
print(zero_arr)
zero_arr[5]=1
print(zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
arr = [1,2,0,0,4,0]
rev = np.flip(arr)
print(rev)

[0 4 0 0 2 1]


In [ ]:
array = np.zeros((5, 5), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Top border
array[-1, :] = 1  # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1  # Right border

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np

# Create an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
checkerboard[::2, ::2] = 1  # Fill 1 at even rows and even columns
checkerboard[1::2, 1::2] = 1  # Fill 1 at odd rows and odd columns

print(checkerboard)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


**Problem - 3: Array Operations:**

In [5]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Arrays:")
print("x =", x)
print("y =", y)
print("v =", v)
print("w =", w)
print()


Arrays:
x = [[1 2]
 [3 5]]
y = [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]



In [ ]:
print("1. Addition of x and y:")
print(x + y)

print("2. Subtraction of y from x:")
print(x - y)

print("3. Multiply x by 2:")
print(x * 2)

print("4. Square of each element in x:")
print(np.square(x))


1. Addition of x and y:
[[ 6  8]
 [10 13]]
2. Subtraction of y from x:
[[-4 -4]
 [-4 -3]]
3. Multiply x by 2:
[[ 2  4]
 [ 6 10]]
4. Square of each element in x:
[[ 1  4]
 [ 9 25]]


In [ ]:
print("5. Dot products:")
print("v . w =", np.dot(v, w))
print("x . v =")
print(np.dot(x, v))
print("x . y =")
print(np.dot(x, y))


5. Dot products:
v . w = 219
x . v =
[29 77]
x . y =
[[19 22]
 [50 58]]


In [8]:
concat_xy = np.concatenate((x, y), axis=0)  # Along rows
concat_vw = np.vstack((v, w))  # Along columns
print("Concatenation of x and y: ",concat_xy)
print("Concatenation of v and w: ",concat_vw)



Concatenation of x and y:  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w:  [[ 9 10]
 [11 12]]


In [7]:
try:
    result = np.concatenate((x, v), axis=0)
    print(result)
except ValueError as e:
    print(f"Error occurred: {e}")

Error occurred: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


The error occured because x and v have different dimensions i.e. x has 2 row and v doesnt have same row. Thererfore, the number of rows and columns must be same in order to concatinate two arrays.

**Problem - 4: Matrix Operations:**

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
B_T_A_T = np.dot(B_T, A_T)

are_equal = np.array_equal(AB_T, B_T_A_T)

print("(AB)^T:", AB_T)
print("B^T A^T:", B_T_A_T)
print("Is (AB)^T equal to B^T A^T? ", are_equal)

(AB)^T: [[19 43]
 [22 50]]
B^T A^T: [[19 43]
 [22 50]]
Is (AB)^T equal to B^T A^T?  True


In [ ]:
import time

list1, list2 = range(1_000_000), range(1_000_000)
start = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
time_list = time.time() - start

array1, array2 = np.arange(1_000_000), np.arange(1_000_000)
start = time.time()
array_sum = array1 + array2
time_numpy = time.time() - start

print(f"Python lists: {time_list:.3f}s, NumPy arrays: {time_numpy:.3f}s")

Python lists: 0.132s, NumPy arrays: 0.015s


In [ ]:
list1, list2 = range(1_000_000), range(1_000_000)

start = time.time()
list_product = [x * y for x, y in zip(list1, list2)]
time_list = time.time() - start

array1, array2 = np.arange(1_000_000), np.arange(1_000_000)

start = time.time()
array_product = array1 * array2
time_numpy = time.time() - start

print(f"Python lists: {time_list:.3f}s, NumPy arrays: {time_numpy:.3f}s")

Python lists: 0.129s, NumPy arrays: 0.005s
